export const words = [
    { pl: 'dodatkowy', en: 'additional' },
    { pl: 'rozważać', en: 'consider' },
    { pl: 'zarząd', en: 'board' },
    { pl: 'doświadcznie', en: 'experience' },
    { pl: 'zdradzić', en: 'betray' },
    { pl: 'raz', en: 'once' },
    { pl: 'przykład', en: 'instance' },
    { pl: 'dostępny', en: 'available' },
    { pl: 'może', en: 'might' },
    { pl: 'jeśli, czy', en: 'whether' },
    { pl: 'wartość', en: 'worth' },
    { pl: 'zapasy magazynowe', en: 'stock' },
    { pl: 'jednak', en: 'however' },
    { pl: 'żródło', en: 'source' },
    { pl: 'twórczy', en: 'creative' },
    { pl: 'aż do', en: 'until' },
    { pl: 'dostęp', en: 'access' },
    { pl: 'narzekać', en: 'complain' },
    { pl: 'zaklepać miejsce z przodu', en: 'shotgun' },
    { pl: 'różnorodność', en: 'variety' },
    { pl: 'dodać', en: 'add' },
    { pl: 'handel, umowa', en: 'deal' },
    { pl: 'utrzymać, konserwować', en: 'maintain' },
    { pl: 'zakres', en: 'range' },
    { pl: 'zawierać', en: 'include' },
    { pl: 'nagłówek', en: 'heading' },
    { pl: 'ludzki', en: 'human' },
    { pl: 'przerażony', en: 'scared' },
    { pl: 'skupiać się', en: 'focus' },
];
